"""empty message

Revision ID: 450be50d70ad
Revises: 
Create Date: 2020-09-19 11:33:19.424249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450be50d70ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tile_density',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tileDate', sa.Date(), nullable=True),
    sa.Column('tileId', sa.String(length=12), nullable=True),
    sa.Column('density', sa.String(length=40), nullable=True),
    sa.Column('maleProportion', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiles',
    sa.Column('tileId', sa.String(length=12), nullable=False),
    sa.Column('munId', sa.String(length=5), nullable=True),
    sa.Column('llx', sa.String(length=40), nullable=True),
    sa.Column('lly', sa.String(length=40), nullable=True),
    sa.Column('urx', sa.String(length=40), nullable=True),
    sa.Column('ury', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('tileId'),
    sa.UniqueConstraint('tileId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tiles')
    op.drop_table('tile_density')
    # ### end Alembic commands ###
